name: Citizensâ€™ Handbook
highlights: false
safe: true
exclude:
    - LICENSE.md
    - README.md
    - less
    - bootstrap
    - fontawesome
    - bower_components/bourbon
    - bower_components/css-smart-grid
    - Gruntfile.js
    - package.json
    - sass
    - sass/*
include:
    - bower_components/leaflet
timezone: "America/New_York"
future: false
permalink: "/:categories/:title/"
domain: ""
markdown: kramdown
google_api_key: AIzaSyAJAQ_ie1uOT3R-tsx0nyIM_MOnyevqlZw
sunlight_api_key: 27085cc0c32c4392966cbb878ab782c7
