name: Citizensâ€™ Handbook
pygments: false
safe: true
exclude:
    - LICENSE.md
    - README.md
    - less
    - bootstrap
    - fontawesome
timezone: "America/New_York"
future: false
permalink: "/:categories/:title/"
# domain: "http://public-information-group.github.io/citizens-handbook"
domain: "http://localhost:4000/"
